### ISSUE TITLE
Request to help maintain

### ISSUE THREAD

**Issue by Firstyear** [openSUSE/obs-service-cargo_vendor#10]
Hi there,

I've had this accepted to opensuse:tools now, and I'm working to have this included in obs. It would be great if we could unblock the PR here, and I'd be happy to help contribute to this. Is there some way we can work on this together? 

Thanks!

**Comment by saschagrunert** [comment]
Hey, sorry for the delay. I was waiting if the original author wants to contribute further to this project but it seems that I'm no alone. If you want then you can help supporting this project and I'll be more responsive in the future. :)

**Comment by Firstyear** [comment]
I'd love to help out more, as I'm pretty invested in getting improved rust/cargo support into obs. I'll give this latest update a try and then it might be good to tag a release so that I can push this to opensuse:tools, and I can start on the process to get it running on obs proper for people to use.

**Comment by saschagrunert** [comment]
Sounds good to me, just ping me if you need anything :)

**Comment by Firstyear** [comment]
Great, I just tested this with a package that had been giving me some grief on the former version, so if we could tag this as v0.3.0, I'll get it released and into obs and start getting the wheels moving to have it as part of build.opensuse.org :) Thanks so much!

**Comment by saschagrunert** [comment]
Sure thing, here we go: https://github.com/openSUSE/obs-service-cargo_vendor/releases/tag/v0.3.0
