### ISSUE TITLE
Old files left in vendor directory

### ISSUE THREAD

**Issue by etam** [openSUSE/obs-service-cargo_vendor#16]
I was updating helvum package (https://build.opensuse.org/package/show/multimedia:apps/helvum). According to wiki (https://en.opensuse.org/Packaging_Rust_Software#Updating_your_Package) I was supposed to just run `osc service runall` to get everything updated.

What I got instead was this: https://github.com/EmbarkStudios/cfg-expr/issues/34
A package `cfg-expr` had an update, where files `src/expr/mod.rs` and `src/targets/mod.rs` were present in earlier version, but were removed in newer version. After running the service those files were still present in `vendor.tar.xz`.

I had to delete `vendor.tar.xz` manually and run the service again, to get a working build.

**Comment by Firstyear** [comment]
Which version of obs-service-cargo_vendor were you using?

**Comment by etam** [comment]
I'm on Tumbleweed
```
> rpm -q obs-service-cargo_vendor
obs-service-cargo_vendor-0.4.3~git0.afec7bc-1.1.noarch
```

**Comment by Firstyear** [comment]
Older versions of obs cargo_vendor didn't clean up properly, but the latest one does, so I think this is already resolved. I've just done an obs checkout and ran service ra 3 times in a row, and they all passed, and vendor isn't left over in the dir. Sorry about the issues.
