### ISSUE TITLE
Missing --no-track option for cargo install

### ISSUE THREAD

**Issue by etam** [openSUSE/obs-service-cargo_vendor#17]
In #7 a message was added, which gives a template `%install` section. It causes cargo to install `/usr/.crates.toml` and `/usr/.crates2.json` files.
According to https://wiki.archlinux.org/title/Rust_package_guidelines#Notes_about_using_cargo_install it's needed to add `--no-track` option to `cargo install` command.

This template is also inconsistent with https://en.opensuse.org/Packaging_Rust_Software#Creating_the_Package

**Comment by Firstyear** [comment]
@etam We are working on this by re-doing some of the macros for cargo at the moment. See https://github.com/Firstyear/cargo-packaging for a draft of this that we will put into devel:lang:rust soon.
