### ISSUE TITLE
Support vendor for multiple source

### ISSUE THREAD

**Issue by J-ZhengLi** [openSUSE/obs-service-cargo_vendor#18]
**Summary**
I came across a scenary where I need to include the files for multiple Rust application in my package, and the _service of it looks like:

```xml
<service name="tar_scm">
  <param name="filename">app_a</param>
  ...
</service>
<service name="tar_scm">
  <param name="filename">app_b</param>
  ...
</service>
<service name="cargo_vendor">
  <param name="srcdir">app_a</param>
</service>
<service name="cargo_vendor">
  <param name="srcdir">app_b</param>
</service>
```

But the problem is the output of this server generate `vendor.tar.gz` and `cargo_config` twice and overriding the previous one, so I have to run them separately. I think it would be nicer to also have a `filename` parameter or the output can have an option be `srcdir.vendor.tar.gz` etc.

If there's an alternative solution please let me know :)

**Comment by Firstyear** [comment]
No problem! I've added a "tag" parameter that will generate "vendor-{tag}.tar.{compression}" and "cargo_config_{tag}". That way you can tag each one individually. 

I'll just update the readme as I did a few updates yesterday too, and I'll get it published to obs ASAP. Thanks!

**Comment by Firstyear** [comment]
https://build.opensuse.org/request/show/967173
