### ISSUE TITLE
should we vendor libraries with the version in the Cargo.lock?

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-service-cargo_vendor#21]
Or at least have an option for it? I ran into trouble from the updating:

https://github.com/nextcloud/notify_push/issues/212

**Comment by Firstyear** [comment]
What you are asking for is to run with --locked, which would be the opposite to "update=true". It's probably not hard to add.

**Comment by Firstyear** [comment]
Fixed

**Comment by darix** [comment]
can you do a release as well?
