### ISSUE TITLE
globbed srctar and srcdir?

### ISSUE THREAD

**Issue by mcepl** [openSUSE/obs-service-cargo_vendor#24]
With all other services which are included in `_service` files it is usually Write-Once-and-Forget type of action. It seems to me that in the case of `cargo_vendor` service the only problem is the need to put full name of either `srcdir` or `srctar`, when in most cases I have found them I have versioned names of them (e.g., `external-editor-revived-*.tar.gz` for https://github.com/Frederick888/external-editor-revived).

Would it be possible to have globbed value accept as well, so that I could write for example?

```xml
<services>
  <service name="cargo_vendor" mode="disabled">
     <param name="srctar">external-editor-revived-*.tar.gz</param>
     <param name="compression">xz</param>
     <param name="update">true</param>
  </service>
  <service name="cargo_audit" mode="disabled">
     <param name="srctar">external-editor-revived-*.tar.gz</param>
  </service>
</services>
```

**Comment by Firstyear** [comment]
I don't see a reason why not? I don't have time this week, but maybe next I can have a look. Or if you want it sooner, I'm always open to PR's.

**Comment by Firstyear** [comment]
Fixed in master

**Comment by mcepl** [comment]
The same should go to `obs-service-cargo-audit`.

**Comment by mcepl** [comment]
@Firstyear https://build.opensuse.org/request/show/1067601
