### ISSUE TITLE
feature/fix: add `sync` option

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_vendor#28]
# Use of `sync` flag in `cargo vendor`

`cargo vendor` provides a `--sync` flag option that you can be used in multiples e.g. `cargo vendor --sync path/to/Cargo.toml --sync another/path/to/Cargo.toml`.

# Rationale

Ideally, `cargo vendor` by itself is sufficient enough to vendor the dependencies of a rust project/crate. However, if there are multiple crates in a project, some of these crates have dependencies that *may differ* from the other crates or the whole project. And sometimes, `cargo vendor` won't be enough because it may miss some of those dependencies from the other crates. Thus, `obs-service-cargo_vendor` is affected by this and cause some rust software to build incorrectly in openSUSE Build Service.

Projects I tested for this behavior are of the following:

- [wezterm](https://github.com/wez/wezterm)
- [jay](https://github.com/mahkoh/jay)

# Proposal

I believe that adding `sync` for `obs-service-cargo_vendor` fixes the issue I have on those projects and other projects that have multiple crates e.g. [zellij](https://github.com/zellij-org/zellij).

## Adding `sync` parameter

`sync` parameter needs to have additional sub-parameters, otherwise, this option will auto detect (recurse) on the root project directory to check for `Cargo.toml` files (by default `auto` is set to `true`). However, setting `auto` to `true` does not guarantee that the dependencies are for the project e.g. some projects have `examples` directory. Ideally, explicitly declaring other sub-parameters for `sync` should be included. Here are the following sub-parameters.

- `exclude_toml`. Excludes paths to Cargo.toml files. This can be used multiple times. Disabled if `auto` is `false`.
- `exclude_dir`. Exclude paths if doing recursive search e.g. examples directory. This can be used multiple times. Disabled if `auto` is `false`.
- `auto`. This is for combining the ability to auto detect. If set to `true`, recursive search is enabled. Otherwise, disabled. Default `true`. Not needed if `sync` has no other sub-parameters.
- `srcsync`. Paths to other Cargo.toml files for vendoring. This can be used multiple times. This can be combined with `auto` and other sub-parameters.

---

I hope this will be discussed since there are too many options here. I do believe that `srcsync` should be sufficient enough since most rust projects have at most 10 sub-crates. And anyone can just use `find` or `fd` to look for other Cargo.toml files and just copy+paste them. I also understand if this proposal is rejected. But I want to be lazy so you should too :P

**Comment by Firstyear** [comment]
@uncomfyhalomacro I think there may be a simpler and more intuitive way to do this. I think we could have an extra param for `cargo.toml` which can be specified multiple times, and each time after the first implies --sync in how we build the command.

That way your _service would become:

```
<services>
  <service name="obs_scm" mode="disabled">
    ...
  </service>
  <service name="cargo_vendor" mode="disabled">
    <param name="srcdir">projectname</param>
    <param name="cargotoml">relative/path/to/Cargo.toml</param>  <- would be passed to --manifest-path
    <param name="cargotoml">another/relative/path/to/Cargo.toml</param>  <- would be --sync
    <param name="cargotoml">more/relative/path/to/Cargo.toml</param>   <-  would be --sync
    <param name="compression">zst</param>
    <param name="update">true</param>
  </service>
</services>
```

I think that would be a simpler way to lay this out parameter wise while still achiving your goal. It also means not listing a cargo.toml implies the recursive auto search as it currently exists. What do you think?

**Comment by uncomfyhalomacro** [comment]
I think that's a good idea! And we should add `excludedir` so autosearch won't search in those directories. usually projects contain examples with their own Cargo.toml
