### ISSUE TITLE
Reduce vendoring size

### ISSUE THREAD

**Issue by flukejones** [openSUSE/obs-service-cargo_vendor#37]
Vendoring should consider using https://github.com/coreos/cargo-vendor-filterer

This can avoid packaing many unrequired crates such as the absurd amount of Windows cruft that also includes many built binaries. Leaving these out can reduce some vendoring down to a quarter of the size.

 I changed the command to `output = run_cargo(appDirectory, "vendor-filterer", argsList + ["--platform", "x86_64-unknown-linux-gnu", "vendor"])`.

This is likely going to require either detecting the target triple, or forcing it to be passed as an arg.

**Comment by Firstyear** [comment]
@flukejones This is a good idea. We actually are just in the middle of rewriting this from python to rust, so once that's done, we could consider this next :)

**Comment by uncomfyhalomacro** [comment]
this is cool

**Comment by uncomfyhalomacro** [comment]
@flukejones sadly, inconsistency in `cargo-vendor-filterer` behavior is leading me to close the PR. Until then, if the situation improves, we will revisit this issue. :)

**Comment by uncomfyhalomacro** [comment]
for now, I and firstyear will just say that the current compression algos/tools we use really reduced tarball sizes. Maybe I can fork `cargo-vendor-filterer` or write my own but that's a PITA and I don't have time to do so, unfortunately 😭

**Comment by uncomfyhalomacro** [comment]
As of now, there are no better way to do it or it still needs a re-discussion. Closing for now.

**Comment by flukejones** [comment]
@uncomfyhalomacro what is the inconsistency?

**Comment by uncomfyhalomacro** [comment]
see #48. *i have some comments there*

**Comment by uncomfyhalomacro** [comment]
Closed as completed in #77
