### ISSUE TITLE
Auto-generate OBS service files

### ISSUE THREAD

**Issue by diconico07** [openSUSE/obs-service-cargo_vendor#41]
The XML service files could be auto-generated from the clap command object (akin to what [clap_mangen](https://crates.io/crates/clap_mangen) does), this would ensure they are always up-to-date.

As a side note, having these up-to-date is important to be able to use the service server-side (as part of a CI/SCM workflow for example).

**Comment by uncomfyhalomacro** [comment]
actually this is what i was planning 2 weeks ago. thanks for reminding
