### ISSUE TITLE
question: keep only one vendored tarball

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_vendor#53]
Using the `--sync` option, a vendored tarball *may* have all the necessary crates described from various manifest files and this vendored tarball can be shared alongside with all subcrates of a project regardless if they are part of a workspace or if they are separate projects entirely.

The question is:
- Are there projects that meet this criteria or requirements?
- And is this really what we want?

**Comment by Firstyear** [comment]
I think it is what we want? s390-tools is the only example I think, but it's also broken in other ways. So I think for now we leave it til we have an example

**Comment by uncomfyhalomacro** [comment]
This is already resolved
