### ISSUE TITLE
structure the test suites better

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_vendor#65]
- Find any weird project configurations
- Add checks if they produced the correct stuff
- Become happy

**Comment by Firstyear** [comment]
It may be a "checklist of actions" rather than a true test suite I think.

**Comment by uncomfyhalomacro** [comment]
so far, no reports of anything breaking. luckily enough, all we wanted is a fine-grained control on compression levels of the archives. stable project indeed.
