### ISSUE TITLE
tumbleweed package update

### ISSUE THREAD

**Issue by ddiss** [openSUSE/obs-service-cargo_vendor#71]
The current openSUSE Factory / Tumbleweed version of obs-service-cargo_vendor appears to be a long way behind upstream. It'd be nice to get an update, or otherwise find out why that's the case.

**Comment by Firstyear** [comment]
Because it was merged into https://build.opensuse.org/package/show/devel:languages:rust/obs-service-cargo, I think we need to delete the other extraneous pkgs.

**Comment by Firstyear** [comment]
Done, request the deletions.

**Comment by uncomfyhalomacro** [comment]
![image](https://github.com/openSUSE/obs-service-cargo_vendor/assets/66054069/9a6b7653-454a-4e19-8ff8-1c10b05fcc59)

Now deleted. Hooray 🥳
