### ISSUE TITLE
cargo vendor functionality needs an option to ignore audit result

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/obs-service-cargo_vendor#72]
Situation:
- I have one security problem that is solved by the update I currently run osc service manualrun on.
- cargo audit still finds something else.
- Now the options are either:
  - delay update until an undefined time when a change is available that pleases audit
  - make the update to the package non-reproducible, by manually calling vendor with instructions to ignore found problems
    - it wants me to say it is not a problem, but if it is, you are saying I should not fix the more pressing issue first

Solution:
setting in _service to ignore audit result

**Comment by Firstyear** [comment]
https://github.com/openSUSE/obs-service-cargo_vendor?tab=readme-ov-file#accepting-risks-of-rustsec-advisories
