### ISSUE TITLE
choose a different service name

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/obs-service-cargo_vendor#75]
In https://github.com/openSUSE/obs-service-cargo_vendor/issues/73#issuecomment-1965536865 you stated, that in essence you do not want to provide compatibility to the obs-service-cargo_vendor that used the name first. Then please choose a different service name and stop replacing it and stop providing it.

```
Repository     : tumbleweed-oss
Name           : obs-service-cargo
Version        : 1.0.0-1.1
[...]
Provides       : [256]
[...]
obs-service-cargo_vendor = 1.0.0
[...]
Conflicts      : [2]
[...]
    obs-service-cargo_vendor
```

**Comment by Firstyear** [comment]
No. Just because you *accidentally* had reproducible builds, doesn't mean we supported them in any capacity.
