### ISSUE TITLE
Sync with rust-packaging

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/obs-service-cargo_vendor#8]
There is another package in openSUSE:Factory, called rust-packaging: https://build.opensuse.org/package/show/openSUSE:Factory/rust-packaging

It provides various rpm-makros for building rust-code (such as `%cargo_build`, `%cargo_install`, ..).

Unfortunately, they use a "hard-coded" path `%{_datadir}/cargo/registry` instead of `vendor`

Right now, one has to do `%define cargo_registry $(pwd)/vendor` before calling any of those makros.

It would be really helpful, if there could be an alignment between your package and rust-packaging (not saying you have to change your service. Maybe you could reach out to the maintainer of rust-packaging).

**Comment by Firstyear** [comment]
It looks like rust-packaging has gone pretty well unmaintained in OBS, so I'm not sure it's worth while to do this. It may be better to lift-and-shift our own macros to supplement these instead.

**Comment by Firstyear** [comment]
Closing, we are removing rust-packaging.
